### ISSUE TITLE
GotoAPIを作りました

### ISSUE THREAD

**Issue by waki285** [TwoSquirrels/GoToBot#6]
質問させていただきます。
これを使用し、叩くとGotoImageができるAPIを作りました。
これを自分のBotに使用してよろしいですか？

**Comment by TwoSquirrels** [comment]
Apache-2.0ライセンスを守っていれば自由に使ってもらってかまいません。

Apache-2.0ライセンスは簡単に言うと、「好きに使ってもいいけど、公開するときはちゃんと僕が作ったって事をどっかに書いてApache-2.0かそれより厳しいライセンスをつけてね。特許とかあったらそこだけうまくやってね。」って感じです。

**Comment by waki285** [comment]
了解です。あなたのことを明記して使わせていただきます。
